# Generated by Django 5.0.4 on 2024-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
