# Generated by Django 5.0.4 on 2024-04-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_book_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
    ]
