# Generated by Django 5.0.4 on 2024-04-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_author_date_of_birth_alter_author_name_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(upload_to='catalogue/images')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_image', to='catalogue.book')),
            ],
        ),
    ]
